server:
  port: 8080
  error:
    include-message: always
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tgbot_shelter
    username: tgbot_user
    password: jB9g_wEp$=
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  jackson:
    serialization:
      indent-output: true
  liquibase:
    change-log: classpath:db/changelog-master.yml
logging:
  level:
    org:
      hibernate:
        SQL: debug
      springframework:
        cache: trace

# Constants
telegram:
  bot:
    token: 5895922485:AAEbBHnL7nO9d2H-WHhl6yC7G3fBTERiqQk

