-- liquibase formatted sql

-- changeset atrilos:1
CREATE TABLE shelter_details
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    map_url             VARCHAR(255),
    safety_instructions OID,
    working_hours       VARCHAR(255)                            NOT NULL,
    CONSTRAINT shelter_details_pkey PRIMARY KEY (id)
);
-- rollback drop table shelter_details;

-- changeset atrilos:2
CREATE TABLE users
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    chat_id      BIGINT                                  NOT NULL,
    is_admin     BOOLEAN DEFAULT FALSE,
    is_volunteer BOOLEAN DEFAULT FALSE,
    email        VARCHAR(255),
    phone_number VARCHAR(20),
    CONSTRAINT users_pkey PRIMARY KEY (id)
);
-- rollback drop table users;

-- changeset atrilos:3
ALTER TABLE users
    ADD CONSTRAINT uq_chat_id UNIQUE (chat_id);
-- rollback alter table users drop constraint uq_chat_id;

