-- liquibase formatted sql

-- changeset atrilos:10
CREATE TABLE pet
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255),
    pet_type   VARCHAR(255)                            NOT NULL,
    color      VARCHAR(255)                            NOT NULL,
    shelter_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_pet PRIMARY KEY (id)
);
-- rollback drop table pet;

-- changeset atrilos:11
ALTER TABLE pet
    ADD CONSTRAINT FK_PET_ON_SHELTER FOREIGN KEY (shelter_id) REFERENCES shelter_details (id);
-- rollback alter table pet drop constraint FK_PET_ON_SHELTER;

-- changeset atrilos:12
alter table pet
    drop constraint fk_pet_on_shelter;
-- rollback ALTER TABLE pet
-- rollback ADD CONSTRAINT FK_PET_ON_SHELTER FOREIGN KEY (shelter_id) REFERENCES shelter_details (id);

-- changeset atrilos:13
alter table pet
    add constraint fk_pet_on_shelter
        foreign key (shelter_id) references shelter_details
            on delete cascade;
-- rollback alter table pet drop constraint fk_pet_on_shelter;